#######################
# Aurea Central Jervis
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-jervis
# This project is based on https://github.com/samrocketman/jervis
language: shell

script:
  - echo "Here you'll build your artifacts. Version Ubuntu stable"

branches:
  only:
    - master
     
jenkins:
  platform: docker
  # lifecycles_standard_stable.json
  os: ubuntu1604
  stability: stable
  sudo: sudo
