#######################
# Aurea Central Jervis
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-jervis
# This project is based on https://github.com/samrocketman/jervis
language: shell

script:
  - echo "Here you'll build your artifacts. Version 2"
  
after_success:
  - echo "This works! "
 
after_failure:
  - echo "This failed"
 
branches:
  only:
    - master
     
jenkins:
  platform: docker
  # lifecycles_standard_stable.json
  os: windows
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaS
